title: An Illustrated Dive

description: >- # this means to ignore newlines until "baseurl:"
  Wip.
url: "https://anillustrateddive.com" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
# theme:
# plugins:
#   - jekyll-feed
